### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nateberkopec**
As for your final question, definitely ask Sam. I think result looks like a bug.

### CODE REVIEW

**Comment by benoittgt** [comment]
Thanks @nateberkopec. And yes first mention (allocated vs retained) was related to memory_profiler.

**Comment by benoittgt** [comment]
Sorry @SamSaffron to ping you but if you have any idea for the last question. 😉

**Comment by SamSaffron** [comment]
what is the "last question" ?

**Comment by benoittgt** [comment]
Hello
Sorry I should have mention the title of the question : 
@SamSaffron https://github.com/benoittgt/understand_ruby_memory#why-when-using-a-frozen-string-we-dont-allocate-memory-  
Thanks

**Comment by SamSaffron** [comment]
I think cause it was allocated earlier when the ruby code was parsed. You can confirm this by loading a file and putting the load in a mem profiler block.

**Comment by benoittgt** [comment]
Ok Sam will give a try.

**Comment by benoittgt** [comment]
I used `File.read` instead of a string a result seems coherent now : 
https://github.com/benoittgt/understand_ruby_memory/pull/8

```ruby
require 'memory_profiler'

report_1 = MemoryProfiler.report do
  def get_me_directly
    File.read('1.txt')
  end
  100.times { get_me_directly }
end

report_2 = MemoryProfiler.report do
  ST = File.read('2.txt')
  def get_me_with_constant
    ST
  end
  100.times { get_me_with_constant }
end

report_3 = MemoryProfiler.report do
  ST_FREEZE = File.read('3.txt').freeze
  def get_me_with_constant_freeze
    ST_FREEZE
  end
  100.times { get_me_with_constant_freeze }
end

puts ' With get_me_directly '.center(50, '✨')
report_1.pretty_print
# Allocated String Report
# -----------------------------------
#        200  "1.txt"
#        200  memory_freeze_benchmark.rb:5
#
#        100  ""
#        100  memory_freeze_benchmark.rb:5
#
#
# Retained String Report
# -----------------------------------

puts "\n"
puts ' With get_me_with_constant '.center(50, '✨')
report_2.pretty_print
# Allocated String Report
# -----------------------------------
#          2  "2.txt"
#          2  memory_freeze_benchmark.rb:11
#
#          1  ""
#          1  memory_freeze_benchmark.rb:11
#
#
# Retained String Report
# -----------------------------------
#          1  ""
#          1  memory_freeze_benchmark.rb:11

puts "\n"
puts ' With get_me_with_constant_freeze '.center(50, '✨')
report_3.pretty_print
# Allocated String Report
# -----------------------------------
#          2  "3.txt"
#          2  memory_freeze_benchmark.rb:19
#
#          1  ""
#          1  memory_freeze_benchmark.rb:19
#
#
# Retained String Report
# -----------------------------------
#          1  ""
#          1  memory_freeze_benchmark.rb:19
```

**Pull request merged**
